blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),
    path('login/', views.login, name='login'),
]

tblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls'))
]

templates/base.html
{% load static %}
{% load blog_extras %}
<!DOCTYPE html>
<html>
	<head>
		<title>天心的博客</title>

		<!-- meta -->
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- css -->
		<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
		 <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
<!--		<link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">-->
		<link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
		<link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

		<!-- js -->
		 <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
<!--		<script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>-->
		 <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
<!--		<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
		<script src="{% static 'blog/js/pace.min.js' %}"></script>
		<script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
		<script src="{% static 'blog/js/bg01.js' %}"></script>
		<link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">

		<style>
			.codehilite {
				padding: 0;
			}

			/* for block of numbers */
			.hljs-ln-numbers {
				-webkit-touch-callout: none;
				-webkit-user-select: none;
				-khtml-user-select: none;
				-moz-user-select: none;
				-ms-user-select: none;
				user-select: none;

				text-align: center;
				color: #ccc;
				border-right: 1px solid #CCC;
				vertical-align: top;
				padding-right: 5px;
			}

			.hljs-ln-n {
				width: 30px;
			}

			/* for block of code */
			.hljs-ln .hljs-ln-code {
				padding-left: 10px;
				white-space: pre;
			}
		</style>
	</head>

	<body>
		<div class="container">
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="{% url 'blog:index' %}"><b>t</b> &amp; blog</a></h1>
							<a href="{% url 'blog:login' %}">登录</a>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
								<button type="button" id="trigger-overlay" class="navbar-toggle">
									<span class="ion-navicon"></span>
								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
								<ul class="nav navbar-nav navbar-right">
									<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
									<li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
									<li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
									<li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon"
									class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="搜索" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
			{% if messages %}
			    {% for message in messages %}
			      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
			        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
			                aria-hidden="true">&times;</span></button>
			        {{ message }}
			      </div>
			    {% endfor %}
			{% endif %}
		</div>
		<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
		<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-8">
						{% block main %}
						{% endblock main %}
					</main>
					<aside class="col-md-4">
						{% block toc %}
						{% endblock toc %}

						{% show_recent_posts %}
						{% show_archives %}
						{% show_categories %}
						{% show_tags %}
						<div class="rss">
							<a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
						</div>
					</aside>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">
							<a>天心的博客</a>
						</p>
						<p style="text-align: center;"><a href="https://beian.miit.gov.cn/" target="_blank" style="color: #0000DD;">粤ICP备2022035886号-1</a></p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="{% url 'blog:index' %}">首页</a></li>
					<li><a href="full-width.html">博客</a></li>
					<li><a href="about.html">关于</a></li>
					<li><a href="contact.html">联系</a></li>
				</ul>
			</nav>
		</div>


		<script src="{% static 'blog/js/script.js' %}"></script>

		<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
		<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js">
		</script>
		<script>
			hljs.initHighlightingOnLoad();
			hljs.initLineNumbersOnLoad();
		</script>

	</body>
</html>